package com.atguigu.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.manager_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.location_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Integer locationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.manager_id
     *
     * @return the value of department.manager_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.manager_id
     *
     * @param managerId the value for department.manager_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.location_id
     *
     * @return the value of department.location_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.location_id
     *
     * @param locationId the value for department.location_id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
}