package com.atguigu.mybatis.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.last_name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sal
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Double sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.deptno
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    private Integer deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.last_name
     *
     * @return the value of employee.last_name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.last_name
     *
     * @param lastName the value for employee.last_name
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sal
     *
     * @return the value of employee.sal
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sal
     *
     * @param sal the value for employee.sal
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setSal(Double sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.deptno
     *
     * @return the value of employee.deptno
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.deptno
     *
     * @param deptno the value for employee.deptno
     *
     * @mbg.generated Sat Aug 21 21:25:58 CST 2021
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }
}